export default{
    name:"banner",
    title:"Banner",
    type:"document",
    fields:[
        {
            name:"banner_image",
            title:"B-Image",
            type:"image",
            options:{
                hotspot:true
            }
        },
        {
            name:"buttonText",
            title:"ButtonText",
            type:"string"
        },
        {
            name:"product",
            title:"Product",
            type:"reference",
            to:[{type:'product'}]
        },
        {
            name:"smallText",
            title:"SmallText",
            type:"string"
        },
        {
            name:"desc",
            title:"Description",
            type:"string"
        },
        {
            name:"midText",
            title:"Mid Text",
            type:"string"
        },
        {
            name:"largeText",
            title:"LargeText",
            type:"string"
        },
        {
            name:"largeText2",
            title:"LargeText2",
            type:"string"
        },
        {
            name:"discount",
            title:"Discount",
            type:"string"
        },
        {
            name:"saleTime",
            title:"SaleTime",
            type:"string"
        }
    ]
}